### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by szabgab**
To run the test on every push.

### CODE REVIEW

**Comment by szabgab** [comment]
One of the test files was only working on Linux so I separated the two.

**Comment by szabgab** [comment]
I wrote about this PR in my Daily CI series: https://dev.to/szabgab/day-3-v2-github-action-ci-for-wsblib-python-3o9b

**Comment by jaedsonpys** [comment]
Thank you for your contribution! Tests at each push are very necessary and you helped me with that!

**Comment by szabgab** [comment]
Hi @jaedsonpys,

I received a lot of value from the open source work of others. This PR was my way of passing on a tiny bit of good deed to someone else. I am trying now to encourage more people, you too, to find other project(s) and make a small contribution there. See this issue explaining my reasoning further: https://github.com/OSDC-Code-Maven/OSDC-Code-Maven.github.io/issues/5

**Pull request merged**
